server:
  port: 10086
spring:
  application:
    name: hello-spring-cloud-eureka
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:10086/eureka/
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost